### ISSUE TITLE
PECL release

### ISSUE THREAD

**Issue by remicollet** [eduardok/libsmbclient-php#22]
What about having this extension in PECL repository to get more visibility ?

**Comment by remicollet** [comment]
Notice: this could ever be a way to have it merged later in php-src.

**Comment by aklomp** [comment]
I like the idea, because Samba extensions are sorely missing from stock PHP. Hence this project. However, we would need a strong project lead to navigate the process. I don't think I fit the role, because after a job change, I no longer spend much time with PHP and Samba. Maybe Eduardo wants to be a promotor?

What is the process like? Do we need to submit this project somewhere?

**Comment by remicollet** [comment]
Process description is there https://pecl.php.net/account-request.php

1st step is an proposal on the pecl-dev mailing list.

Notice: I can help on this, as I already maintains some ext there, https://pecl.php.net/user/remi

P.S. after decision about #21

**Comment by eduardok** [comment]
I just started working for the same company of back then again, so give me a week or two and we try to get to this. Should also be enough to settle on #21 .

**Comment by remicollet** [comment]
See PR #28 for initial package.xml

**Comment by remicollet** [comment]
Who already have a "php" account, and who can take care of a "New extension proposal" mail to pecl-dev@lists.php.net ?

**Comment by eduardok** [comment]
Messaged the list with the introductions :)

**Comment by eduardok** [comment]
Published https://pecl.php.net/package/smbclient
