### ISSUE TITLE
File creation date

### ISSUE THREAD

**Issue by pruimmartin** [eduardok/libsmbclient-php#34]
HI, 

Is it also possible to display file or folder creation date? Using stat of fstat is not returning that information..

Thanks!

**Comment by eduardok** [comment]
You mean, using smbclient_fstat or smbclient_stat is not returning that ?
Please reduce your code to a minimum so we can reproduce the issue.
Thanks

**Comment by pruimmartin** [comment]
It's indeed the smclient_start that is not returning the creation date of a file or folder. My code is:

$stats = smbclient_stat($state, 'smb://'.$server.'/'.$share.'/'.$folder.'/'.$entry['name']);

This line is returning an array with all kind of information about that entry. It's returning the modified timestamp for example, but not the correct one for the creation date.

**Comment by eduardok** [comment]
What is it returning? What is the creation date on Windows?

**Comment by aklomp** [comment]
Hey, the [information returned by `stat`](https://secure.php.net/manual/en/function.stat.php) does not include a file's creation time, because that is not tracked. It returns:

- the atime, which is the last time the contents of the file were accessed;
- the mtime, which is the last time the contents of the file were modified;
- and the ctime, which is the last time the file's inode was modified.

Since a file's inode is usually only modified upon creation, rename or move (but *can* also be modified by innocent stuff like 'touch'), the ctime is probably what you're looking for. But it won't always be equal to the time of a file's creation.

Maybe you can try requesting the file's extended attributes with `smbclient_getxattr()` and see if they contain the data you're interested in. Perhaps Windows does track file creation time and stuffs it in an xattr.
