### ISSUE TITLE
Some big files getting corrupted on rpi/raspian

### ISSUE THREAD

**Issue by MrJackJonesIII** [eduardok/libsmbclient-php#43]
Hey guys,
could you please have a look at this issue I opened in the owncloud section:
https://github.com/owncloud/core/issues/26155#issuecomment-248240043
It looks like there is something wrong with libsmbclient on raspian...

**Comment by aklomp** [comment]
That's unfortunate, but I'm not sure that we're the cause of the problem. `libsmbclient-php` is only a fairly thin wrapper around `libsmbclient`, and it doesn't do much except marshalling data. I'm inclined to say that the real problem is either one layer lower or one layer higher on the stack.

When I look at your error logs, the error that jumps out is the one where `smbclient_state_errno()` is fed an invalid state resource. That shouldn't happen, and leads me to believe that the cause may be one layer higher up the stack, in the thing that calls `libsmbclient-php`. As far as I'm aware, that layer is @icewind1991's [SMB](https://github.com/icewind1991/SMB) library, which uses our library as a backend. I suggest you make the maintainer aware of your issue. The fact that the bug is reproducible is helpful, and means that the chances of getting it fixed are high.

**Comment by eduardok** [comment]
No feedback, assuming resolved elsewhere, as suggested.
