### ISSUE TITLE
Workgroup required for SMB2 connections

### ISSUE THREAD

**Issue by jvillafanez** [eduardok/libsmbclient-php#57]
Checked with unreleased samba 4.8.0 (compiled from https://github.com/samba-team/samba/commit/20fe43472e8c99d9d92df027bc0e604e5bb917b0) and libsmbclient-php 0.9.0 (also compiled against the above)

The test script matches the one shown in the example of this repository, adjusted to connect to the target server.

```
PHP Warning:  Couldn't open SMB directory smb://10.0.2.8/opt: Permission denied in /opt/test.php on line 11
```

Filling the workgroup with any random value solves the problem, as long as the server supports it

@eduardok @aklomp  (sorry if I pinged the wrong people)

**Comment by eduardok** [comment]
Since this is too old I'm going to close given that nobody else mentioned a similar issue. If you can check that this issue still happens with latest releases (libsmbclient and php-smbclient), then by all means comment here. I just rather not spend any time just to find out I cannot reproduce. Thanks

**Comment by jvillafanez** [comment]
I cannot reproduce it any longer with libsmbclient 4.11 for the client and also 4.11 for the server as well as windows server 2016 (php-libsmbclient 1.0.0). Either samba fixed the problem (if any) or I did something wrong. In any case, there is nothing to do here.
